version: '3'

services:

  api-upload-database:
    image: postgres:14-alpine
    container_name: api-upload-database
    restart: on-failure
    volumes:
      - ./.docker/database/postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-api_upload_xml}
    networks:
      - api-upload-xml

networks:
  api-upload-xml: